Repository mocacong-hackathonKU/godsaeng, pull requests merged in 2023-08, with the labels that each got.

#1 feat: ci/cd
  .github/workflows/cd-backend.yml
  .github/workflows/ci-backend.yml
  .gitignore
  server/build.gradle
  server/docker-compose.yml
  server/dockerfile
Labels: enhancement

#2 feat: ci cd test
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd-backend.yml
  .github/workflows/ci-backend.yml
  server/build.gradle
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/resources/application.yml
Labels: bug, enhancement

#8 feat: 이메일 회원가입 및 로그인 추가
  server/src/main/java/godsaeng/server/config/SecurityConfig.java
  server/src/main/java/godsaeng/server/controller/AuthController.java
  server/src/main/java/godsaeng/server/controller/MemberController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/GodSaengMember.java
  server/src/main/java/godsaeng/server/domain/Member.java
  server/src/main/java/godsaeng/server/domain/Platform.java
  server/src/main/java/godsaeng/server/dto/request/AuthLoginRequest.java
  server/src/main/java/godsaeng/server/dto/request/MemberSignUpRequest.java
  server/src/main/java/godsaeng/server/dto/response/IsDuplicateEmailResponse.java
  server/src/main/java/godsaeng/server/dto/response/MemberSignUpResponse.java
  server/src/main/java/godsaeng/server/dto/response/TokenResponse.java
  server/src/main/java/godsaeng/server/exception/badrequest/DuplicateMemberException.java
  server/src/main/java/godsaeng/server/exception/badrequest/DuplicateNicknameException.java
  server/src/main/java/godsaeng/server/exception/badrequest/InvalidEmailException.java
  server/src/main/java/godsaeng/server/exception/badrequest/InvalidPasswordException.java
  server/src/main/java/godsaeng/server/exception/badrequest/PasswordMismatchException.java
  server/src/main/java/godsaeng/server/repository/MemberRepository.java
  server/src/main/java/godsaeng/server/service/AuthService.java
  server/src/main/java/godsaeng/server/service/MemberService.java
  server/src/test/java/godsaeng/server/security/EncryptUtilsTest.java
  server/src/test/java/godsaeng/server/security/auth/AuthorizationExtractorTest.java
  server/src/test/java/godsaeng/server/security/auth/JwtTokenProviderTest.java
  server/src/test/java/godsaeng/server/service/AuthServiceTest.java
  server/src/test/java/godsaeng/server/service/MemberServiceTest.java
Labels: enhancement

#6 feat: AWS S3 연동 및 프로필 이미지 수정 API 구현
  server/build.gradle
  server/src/main/java/godsaeng/server/controller/MemberController.java
  server/src/main/java/godsaeng/server/domain/Member.java
  server/src/main/java/godsaeng/server/exception/badrequest/InvalidFileEmptyException.java
  server/src/main/java/godsaeng/server/repository/MemberRepository.java
  server/src/main/java/godsaeng/server/service/MemberService.java
  server/src/main/java/godsaeng/server/support/AwsS3Uploader.java
  server/src/main/resources/application.yml
  server/src/test/java/godsaeng/server/service/MemberServiceTest.java
  server/src/test/resources/application.yml
  server/src/test/resources/images/test_img.jpg
  server/src/test/resources/images/test_img2.jpg
Labels: enhancement

#10 feat: 인증 등록 POST API 구현
  server/src/main/java/godsaeng/server/controller/GodSaengController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/Proof.java
  server/src/main/java/godsaeng/server/domain/ProofImage.java
  server/src/main/java/godsaeng/server/dto/request/ProofSaveRequest.java
  server/src/main/java/godsaeng/server/dto/response/ProofSaveResponse.java
  server/src/main/java/godsaeng/server/exception/badrequest/DuplicateProofException.java
  server/src/main/java/godsaeng/server/exception/badrequest/InvalidProofMemberException.java
  server/src/main/java/godsaeng/server/exception/badrequest/InvalidProofStatusException.java
  server/src/main/java/godsaeng/server/exception/badrequest/NotExistsProofImageException.java
  server/src/main/java/godsaeng/server/repository/GodSaengMemberRepository.java
  server/src/main/java/godsaeng/server/repository/ProofImageRepository.java
  server/src/main/java/godsaeng/server/repository/ProofRepopsitory.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
Labels: enhancement

#13 style: proofImg 변수명 수정 및 카카오 리다이렉트 URI 수정
  server/src/main/java/godsaeng/server/controller/GodSaengController.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
Labels: enhancement

#14 feat: PR template 문서 작성
  .github/pull_request_template.md
Labels: documentation

#15 feat: 월간 조회 기능 구현
  server/src/main/java/godsaeng/server/controller/GodSaengController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/GodSaengStatus.java
  server/src/main/java/godsaeng/server/domain/GodSaengWeek.java
  server/src/main/java/godsaeng/server/domain/Week.java
  server/src/main/java/godsaeng/server/dto/response/MonthlyGodSaengResponse.java
  server/src/main/java/godsaeng/server/dto/response/MonthlyGodSaengsResponse.java
  server/src/main/java/godsaeng/server/repository/GodSaengRepository.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/domain/GodSaengTest.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
Labels: enhancement

#17 fix: OpenedDate의 기준 시간 이슈로 인한 월간 조회 기능 수정
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/GodSaengStatus.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/domain/GodSaengTest.java
Labels: bug

#16 fix: 회원가입 로직을 프로필 이미지도 함께 등록하도록 수정
  server/src/main/java/godsaeng/server/controller/MemberController.java
  server/src/main/java/godsaeng/server/domain/Member.java
  server/src/main/java/godsaeng/server/service/MemberService.java
  server/src/test/java/godsaeng/server/service/MemberServiceTest.java
Labels: enhancement

#19 feat: 회원 탈퇴 DELETE API 추가 및 이벤트 리스너 적용
  server/src/main/java/godsaeng/server/controller/MemberController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/GodSaengMember.java
  server/src/main/java/godsaeng/server/domain/Proof.java
  server/src/main/java/godsaeng/server/repository/GodSaengMemberRepository.java
  server/src/main/java/godsaeng/server/repository/GodSaengRepository.java
  server/src/main/java/godsaeng/server/repository/ProofRepository.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/main/java/godsaeng/server/service/MemberService.java
  server/src/main/java/godsaeng/server/service/event/DeleteMemberEvent.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
  server/src/test/java/godsaeng/server/service/MemberServiceTest.java
Labels: enhancement

#18 feat: 일간 같생 목록 조회 API 구현
  server/src/main/java/godsaeng/server/controller/GodSaengController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/dto/response/DailyGodSaengResponse.java
  server/src/main/java/godsaeng/server/dto/response/DailyGodSaengsResponse.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
Labels: enhancement

#21 fix: S3 연결 설정 정보 수정
  server/src/test/resources/application.yml
Labels: bug

#22 feat: 같생 상세 조회 기능 구현
  server/src/main/java/godsaeng/server/controller/GodSaengController.java
  server/src/main/java/godsaeng/server/controller/MemberController.java
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/dto/response/GodSaengDetailResponse.java
  server/src/main/java/godsaeng/server/dto/response/GodSaengMemberResponse.java
  server/src/main/java/godsaeng/server/dto/response/ProofResponse.java
  server/src/main/java/godsaeng/server/repository/MemberRepository.java
  server/src/main/java/godsaeng/server/repository/ProofRepository.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
Labels: enhancement

#24 feat: 같생 일간 조회에 isDone 정보 추가
  server/src/main/java/godsaeng/server/domain/GodSaeng.java
  server/src/main/java/godsaeng/server/domain/Proof.java
  server/src/main/java/godsaeng/server/dto/response/DailyGodSaengResponse.java
  server/src/main/java/godsaeng/server/dto/response/GodSaengDetailResponse.java
  server/src/main/java/godsaeng/server/dto/response/GodSaengResponse.java
  server/src/main/java/godsaeng/server/repository/ProofRepository.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
  server/src/test/java/godsaeng/server/service/GodSaengServiceTest.java
Labels: enhancement

#25 feat: 서버 에러 발생 시 슬랙 알림 기능 구현
  server/build.gradle
  server/src/main/java/godsaeng/server/controller/ControllerAdvice.java
  server/src/main/resources/application.yml
  server/src/test/resources/application.yml
Labels: enhancement

#26 feat: 애플 oauth 키 redis 캐시 적용
  server/build.gradle
  server/src/main/java/godsaeng/server/config/RedisCacheConfig.java
  server/src/main/java/godsaeng/server/config/RedisConfig.java
  server/src/main/java/godsaeng/server/domain/Week.java
  server/src/main/java/godsaeng/server/security/auth/apple/AppleClient.java
  server/src/main/resources/application.yml
  server/src/test/java/godsaeng/server/acceptance/AcceptanceTest.java
  server/src/test/java/godsaeng/server/support/DatabaseCleaner.java
  server/src/test/java/godsaeng/server/support/TestRedisConfig.java
  server/src/test/resources/application.yml
Labels: enhancement

#27 feat: 월간 조회 isDone으로 변경
  server/src/main/java/godsaeng/server/domain/Proof.java
  server/src/main/java/godsaeng/server/dto/response/DailyGodSaengResponse.java
  server/src/main/java/godsaeng/server/dto/response/MonthlyGodSaengResponse.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
Labels: bug, enhancement

#28 fix: ProofImage에서 GodSaeng 엔티티 연관관계 삭제
  server/src/main/java/godsaeng/server/domain/ProofImage.java
  server/src/main/java/godsaeng/server/service/GodSaengService.java
Labels: enhancement

#30 fix: week 오타 수정
  server/src/main/java/godsaeng/server/domain/Week.java
Labels: bug

#29 docs: README.md 초안 작성
  README.md
Labels: documentation
